-- SMS service (httpSMS): schema changes for review in pgAdmin.
-- Design: docs/superpowers/specs/2026-10-04-sms-service-design.md
--
-- Runs as-is against the development database. Inside a transaction so a mistake leaves
-- nothing behind: run it, look at the ERD, then ROLLBACK (or COMMIT to keep it). The real
-- migration (0011) is generated by drizzle-kit from schema.ts once this is approved.

begin;

-- ---------------------------------------------------------------------
-- 1. messages: the outbox columns the sender loop needs
-- ---------------------------------------------------------------------

-- When the sender may send it. now() for most texts; the end of quiet hours for texts written
-- during them. A retry after a failed attempt also pushes it forward.
alter table messages add column send_after timestamptz not null default now();

-- Tries to hand it to httpSMS. After 3 the text is 'failed'.
alter table messages add column attempts smallint not null default 0;

-- The last error from httpSMS (ours or the phone's), for whoever looks at a failed text.
alter table messages add column last_error text;

alter table messages add constraint messages_attempts_range
  check (attempts between 0 and 3);

-- Only outbound texts are sent, so only they count tries.
alter table messages add constraint messages_inbound_no_attempts
  check (direction = 'outbound' or attempts = 0);

-- The sender loop's query: texts not yet handed to httpSMS, oldest due first. Partial, so it
-- stays tiny: a row leaves it as soon as httpSMS takes it.
create index messages_due_idx on messages (send_after)
  where status = 'queued' and provider_message_id is null;

-- ---------------------------------------------------------------------
-- 2. webhook_events: httpSMS events are stored to ignore repeats
-- ---------------------------------------------------------------------

alter table webhook_events drop constraint webhook_events_provider_valid;
alter table webhook_events add constraint webhook_events_provider_valid
  check (provider in ('twilio', 'xendit', 'stripe', 'httpsms'));

-- ---------------------------------------------------------------------
-- 3. Demo data (seed.ts does this; shown here so the ERD review sees real rows)
-- ---------------------------------------------------------------------

-- The demo runs in the Philippines: quiet hours and arrival windows follow Manila time.
update tenants set timezone = 'Asia/Manila' where slug = 'desert';

-- The Android phone running the httpSMS app. Replace the number with the demo SIM's.
-- httpSMS webhooks name this number as `owner`, which is how they find the contractor.
insert into phone_numbers (tenant_id, number, status)
select id, '+639170000000', 'active' from tenants where slug = 'desert';

-- ---------------------------------------------------------------------
-- Look before deciding
-- ---------------------------------------------------------------------

select column_name, data_type, column_default, is_nullable
from information_schema.columns
where table_name = 'messages' and column_name in ('send_after', 'attempts', 'last_error');

select t.slug, t.timezone, p.number, p.status
from tenants t join phone_numbers p on p.tenant_id = t.id;

rollback; -- change to commit to keep it
